Student.delete_all

Student.create name: 'Chandler Moisen',	email: 'chandler.moisen@gmail.com',	github: 'cheshireoctopus',	website: 'http://www.chandlermoisen.com', left_percent: '12.5%', top_percent: '0px'
Student.create name: 'Sunmi Oh', email: 'ohsun14@gmail.com', github: 'ohsunmi', website: 'www.sunmioh.com', left_percent: '22%', top_percent: '5%'
Student.create name: 'Neel Patel', email: 'neelp22@gmail.com', left_percent: '31%', top_percent: '0px'						
Student.create name: 'Heather Wigmore', email: 'wigmore.heather@gmail.com', left_percent: '40.5%', top_percent: '5%'						
Student.create name: 'Scott Norvell', email: 'scottlnorvell@gmail.com', github: 'ScottLNorvell', website: 'http://www.scottlnorvell.com', left_percent: '46%', top_percent: '0px'
Student.create name: 'Cassie Walther', email: 'cassie.walther@gmail.com', left_percent: '59%', top_percent: '7%'
Student.create name: 'Anthony Brancazo',	email: 'a.branc100@gmail.com',	github:'apbran', left_percent: '68.5%', top_percent: '7%'	
Student.create name: 'Adam McCabe',	email: 'ajm845@gmail.com', left_percent: '77%', top_percent: '5%'
Student.create name: 'Alex Gaynor',	email: 'agaynor72@gmail.com', website: 'http://www.noob.com', left_percent: '8%', top_percent: '13%'				
Student.create name: 'Christopher Huyett', email:	'huyettcp@gmail.com', left_percent: '20%', top_percent: '15%'	
Student.create name: 'Samuel Spector', email: 'samalden.spector@gmail.com', left_percent: '31%', top_percent: '17%'	
Student.create name: 'Camila Cano',	email: 'camilacanog@gmail.com',	github: 'camicano', website: 'http://camicano.github.io', left_percent: '43.5%', top_percent: '17%'	
Student.create name: 'Francesca Wedemeyer',	email: 'flwedemeyer@gmail.com', left_percent: '50%', top_percent: '17%'	
Student.create name: 'Wesley Yu', email: 'wesleyhl.yu@gmail.com', left_percent: '62.3%', top_percent: '17%'	
Student.create name: 'Mitul Patel', email: 'mitulp91@gmail.com', left_percent: '68.5%', top_percent: '17%'	
Student.create name: 'Rudy Crespo', email: 'rudycrespo@hushmail.com', github: 'rcrespo9', website: 'http://www.rudycrespo.com', left_percent: '77%', top_percent: '17%'				
Student.create name: 'Matt Marcello', email: 'matt.marcello@gmail.com', github: 'mattmarcello',	website: 'http://www.mattmarcello.com', left_percent: '87%', top_percent: '16%'	
Student.create name: 'Lane Burks', email: 'lcburks@gmail.com', left_percent: '12%', top_percent: '37%'	
Student.create name: 'Javier Fernandez', email: 'jfernadel@gmail.com', github: 'jeivar', website: 'http://jeivar.com', left_percent: '22%', top_percent: '32%'			
Student.create name: 'Joseph Jung', email: 'joej21@gmail.com', github: 'joe21', website:	'http://www.joehjung.com', left_percent: '38%', top_percent: '32%'	
Student.create name: 'Winson Yuan', email: 'winson.yuan@hotmail.com', left_percent: '50%', top_percent: '30%'	
Student.create name: 'Michael Glumac', email: 'mglumac@gmail.com', left_percent: '62.3%', top_percent: '32%'	
Student.create name: 'David Han',	email: 'davidhan527@gmail.com', github: 'davidhan527',	website: 'www.han-david.com', left_percent: '74%', top_percent: '32%'	
Student.create name: 'Stan Kudrow', email: 'st4sik@gmail.com', left_percent: '83%', top_percent: '35%'	 


